### ISSUE TITLE
Can't logout with auto-login.

### ISSUE THREAD

**Issue by las3r** [henriquels25/redux-oidc-sample#1]
Thanks for this amazing sample project, it helped me a lot in implement oidc with redux and PKCE. 

One question I have that doesn't become immediately clear:

I want the user to automatically be redirected to the authorization party (in my case IdentityServer4). This is easy enough by just running ```userManager.signInRedirect()``` from the `login.js` file.

The problem however is that once I use this, I can no longer use the 'logout' feature. Once I logout, the user is never properly logged out from what I can see. The logout is taking place in the client side app, but the user is never redirected to the identityserver in this case. I reproduced this by using the following code for `login.js`:

```
import React from 'react';
import userManager from "../userManager";

const LoginPage = () => {
    userManager.signinRedirect();
    return null;
};

export default LoginPage;
```

You'll see that once you 'logout' it will automatically relogin automatically (probably because it never signs out at the source oidc-server, and then when the page 'refreshes', the silent renewal gets a new token and the user is 'still' logged in, this time with a fresh token.

How do I:
1) Automatically redirect the user to the identityserver properly
2) Have logout still work properly?

THanks

**Comment by henriquels25** [comment]
I am really glad that this sample helped you.

When using the okta profile, I am not getting this behavior. When I click the logout button, I have to enter the user/password again.

The logout button has the following source code:
```javascript
const onLogoutButtonClick = (event) => {
    event.preventDefault();
    userManager.signoutRedirect();
};
```
After the user click this button, the app makes a logout HTT request to the authorization server, as you can see in the following image:
<img width="1266" alt="logout_token" src="https://user-images.githubusercontent.com/4086440/80288408-23e93780-870e-11ea-8c07-4b051512a310.png">

So, in my view, the logout is working properly in this sample, which can be seen by running it with the okta profile (npm run okta).

If that does not make sense for you, please let me know.

**Comment by las3r** [comment]
I've worked this out, in the end it was an error with my template (that was built for okta). I've changed the code a bit and now it works. Basically I had issues with order of execution. This is now fixed. 

Thanks for the help.
